application:
  endpoint-uri: http://localhost:4566
  region: us-east-1

spring:
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/appdb
    username: user
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        id:
          new_generator_mappings: true
          optimizer:
            pooled:
              preferred: pooled-lo
        jdbc:
          batch_size: 25
          lob:
            non_contextual_creation: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true

cloud:
  aws:
    region:
      static: us-east-1
    s3:
      endpoint-url: http://127.0.0.1:4566
      bucket-name: testbucket
      access-key: localstack
      secret-key: localstack
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error