version: '3.8'
services:

  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudwatch, dynamodb, kinesis
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      # - "../.localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - localstack:/tmp/localstack

volumes:
  localstack:
