version: '3.8'
services:

  localstack:
    image: localstack/localstack:2.0.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis, dynamodb
      - DEFAULT_REGION=us-east-1
      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=my-test-stream
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '../.localstack:/docker-entrypoint-initaws.d'
