version: '3.8'
services:

  localstack:
    image: localstack/localstack:2.3.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis, dynamodb, iam
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack:/tmp/localstack

volumes:
  localstack:
