"component: cloudwatch":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-cloudwatch-project/**/*
"component: dynamodb":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-dynamodb-project/**/*
"component: kinesis":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-kinesis-project/**/*
"component: lambda":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-lambda-project/**/*
"component: parameterstore":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-parameterstore-project/**/*
"component: s3":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-s3-project/**/*
"component: secretmanager":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-secretmanager-project/**/*
"component: ses":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-ses-project/**/*
"component: sns":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-sns-project/**/*
"component: sqs":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-sqs-project/**/*
"type: documentation":
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
"type: dependency-upgrade":
  - changed-files:
      - any-glob-to-any-file: 
          - aws-cloudwatch-project/pom.xml
          - aws-dynamodb-project/pom.xml
          - aws-kinesis-project/consumer/pom.xml
          - aws-kinesis-project/producer/pom.xml
          - aws-lambda-project/pom.xml
          - aws-parameterstore-project/pom.xml
          - aws-s3-project/pom.xml
          - aws-secretmanager-project/pom.xml
          - aws-ses-project/pom.xml
          - aws-sns-project/pom.xml
          - aws-sqs-project/pom.xml
