"component: cloudwatch":
  - aws-cloudwatch-project/**/*
"component: s3":
  - aws-s3-project/**/*
"component: parameter-store":
  - aws-parameter-store-project/**/*
"component: secrets-manager":
  - aws-secrets-manager-project/**/*
"component: dynamodb":
  - aws-dynamodb-project/**/*
"component: ses":
  - aws-ses-project/**/*
"component: sns":
  - aws-sns-project/**/*
"component: sqs":
  - aws-sqs-project/**/*
"component: kinesis":
  - aws-kinesis-project/**/*
"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*
"type: dependency-upgrade":
  - aws-cloudwatch-project/pom.xml
  - aws-s3-project/pom.xml
  - aws-parameter-store-project/pom.xml
  - aws-secrets-manager-project/pom.xml
  - aws-dynamodb-project/pom.xml
  - aws-ses-project/pom.xml
  - aws-sns-project/pom.xml
  - aws-sqs-project/pom.xml
  - aws-kinesis-project/pom.xml
