"component: cloudwatch":
  - aws-cloudwatch-project/**/*
"component: dynamodb":
  - aws-dynamodb-project/**/*
"component: kinesis":
  - aws-kinesis-project/**/*
"component: lambda":
  - aws-lambda-project/**/*
"component: parameterstore":
  - aws-parameterstore-project/**/*
"component: s3":
  - aws-s3-project/**/*
"component: secretmanager":
  - aws-secretmanager-project/**/*
"component: ses":
  - aws-ses-project/**/*
"component: sns":
  - aws-sns-project/**/*
"component: sqs":
  - aws-sqs-project/**/*
"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*
"type: dependency-upgrade":
  - aws-cloudwatch-project/pom.xml
  - aws-dynamodb-project/pom.xml
  - aws-kinesis-project/consumer/pom.xml
  - aws-kinesis-project/producer/pom.xml
  - aws-lambda-project/pom.xml
  - aws-parameterstore-project/pom.xml
  - aws-s3-project/pom.xml
  - aws-secretmanager-project/pom.xml
  - aws-ses-project/pom.xml
  - aws-sns-project/pom.xml
  - aws-sqs-project/pom.xml
