github:
  prebuilds:
    addComment: false
    addBadge: true

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 4566-4599
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: public
  - port: 9000
    visibility: public
  - port: 9200
    visibility: public
  - port: 5601
    visibility: public
  - port: 5432
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - ms-azuretools.vscode-docker
    - pivotal.vscode-boot-dev-pack
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-initializr
    - GabrielBB.vscode-lombok
    - redhat.java
