image:
  file: .gitpod.Dockerfile

tasks:
  - before: sdk install mvnd
    init: mvnd verify -DskipTests

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 4566-4599
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: public
  - port: 9000
    visibility: public
  - port: 9200
    visibility: public
  - port: 5601
    visibility: public
  - port: 5432
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - ms-azuretools.vscode-docker
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-maven
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-initializr
    - GabrielBB.vscode-lombok
    - redhat.java
    - VMware.vscode-boot-dev-pack
