cloud:
  aws:
    sqs:
      endpoint: http://localhost:4566
    region:
      static: us-east-1
    stack:
      auto: false
      enabled: false
    credentials:
      secretKey: test
      accessKey: test
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: secret
    url: jdbc:postgresql://localhost:5432/appdb
    username: siva
