logging:
  file:
    name: logs/aws-sqs-project.log
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: ERROR
        util:
          EC2MetadataUtils: ERROR
    sql: INFO
    web: INFO


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info,logfile,loggers,metrics

spring:
  application:
    name: aws-sqs-project
  datasource:
    hikari:
      auto-commit: false
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        id:
          new_generator_mappings: true
          optimizer:
            pooled:
              preferred: pooled-lo
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
    show-sql: true
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
