spring:
  cloud:
    aws:
      credentials:
        secretKey: test
        accessKey: test
      region:
        static: us-east-1
      endpoint: http://localhost:4566
  datasource:
    password: secret
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
