version: '3.8'
services:

  postgresqldb:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"
    environment:
      - EAGER_SERVICE_LOADING=1
      - SERVICES=SECRETSMANAGER
      - DEFAULT_REGION=us-east-1
      - AWS_CBOR_DISABLE=1
    volumes:
      - "../.localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook    
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
