version: '3.8'
services:

  postgresqldb:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=SECRETSMANAGER
      - DEFAULT_REGION=us-east-1
      - AWS_CBOR_DISABLE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '../.localstack:/docker-entrypoint-initaws.d'
