version: '3.8'
services:
  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "../.localstack:/etc/localstack/init/ready.d"  # ready hook
      - localstack:/tmp/localstack

volumes:
  localstack:
