version: '3.8'
services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - '4566-4583:4566-4583'
    environment:
      - DEBUG=1
      - USE_SSL=0
      - AWS_CBOR_DISABLE=1
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/private}:/private"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '../.localstack:/docker-entrypoint-initaws.d'
