version: '3.8'
services:
  localstack:
    image: localstack/localstack:1.0.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ses
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '../.localstack:/docker-entrypoint-initaws.d'
