version: '3.8'
services:
  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,ses
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/private}:/private"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - '../.localstack:/docker-entrypoint-initaws.d'
