name: aws-parameterstore-project

on:
  push:
    paths:
      - "aws-parameterstore-project/**"
    branches: [ main ]
  pull_request:
    paths:
      - "aws-parameterstore-project/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '21' ]
    defaults:
      run:
        working-directory: "./aws-parameterstore-project"
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'
  
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean verify
