name: Main Branch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Unit, Integration Tests & Push to Docker Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set SHA8
        run: echo ::set-env name=SHA8::$(git log --oneline -1 | awk '{print $1}')

      - name: Test SHA8
        run: echo $SHA8

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean install
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Create docker loadbalancer image
        run: docker build -t docker.io/dockertmt/aws-sqs-project:latest -t docker.io/dockertmt/aws-sqs-project:$SHA8 ./aws-sqs-project

      - name: Push docker images
        run: |
          docker push docker.io/dockertmt/aws-sqs-project:latest
          docker push docker.io/dockertmt/aws-sqs-project:$SHA8


